OPS445 Lab Report - System Information for running ./CheckLab7.py
=================================================================
    User login name: sarjina
    Linux system name: fedora
    Python executable: /usr/bin/python3
    Python version: 3123
    OS Platform: linux
    Working Directory: /home/sarjina/ops445/lab7
    Start at: Fri Jul 26 14:08:55 2024
=================================================================

sarjina@fedora:~/ops445/lab7$ python3 ./CheckLab7.py -f -v lab7a
test_0 (__main__.lab7a.test_0)
[Lab 7] - [Investigation 1] - [Part 1] - Test for file creation: ./lab7a.py ... ok
test_1 (__main__.lab7a.test_1)
[Lab 7] - [Investigation 1] - [Part 1] - Test for file creation: ./lab7a1.py ... ok
test_a (__main__.lab7a.test_a)
[Lab 7] - [Investigation 1] - [Part 1] - Test for errors running: ./lab7a1.py ... ok
test_a1 (__main__.lab7a.test_a1)
[Lab 7] - [Investigation 1] - [Part 1] - Test for correct shebang line: ./lab7a1.py ... ok
test_a_instantiate_class_0 (__main__.lab7a.test_a_instantiate_class_0)
[Lab 7] - [Investigation 1] - [Part 1] - Test for Creating object - should fail with 4 arguments ... ok
test_a_instantiate_class_1 (__main__.lab7a.test_a_instantiate_class_1)
[Lab 7] - [Investigation 1] - [Part 1] - Test for Creating object - should fail with string arguments ... ok
test_b1_sum_times (__main__.lab7a.test_b1_sum_times)
[Lab 7] - [Investigation 1] - [Part 1] - Test for sum_times() - should provide the correct output ... ok
test_b2_sum_times (__main__.lab7a.test_b2_sum_times)
[Lab 7] - [Investigation 1] - [Part 1] - Test for sum_times() - should provide the correct output ... ok

----------------------------------------------------------------------
Ran 8 tests in 0.038s

OK
sarjina@fedora:~/ops445/lab7$ python3 ./CheckLab7.py -f -v lab7b
test_0 (__main__.lab7b.test_0)
[Lab 7] - [Investigation 1] - [Part 2] - Test for file creation: ./lab7b.py ... ok
test_a1 (__main__.lab7b.test_a1)
[Lab 7] - [Investigation 1] - [Part 2] - Test for correct shebang line: ./lab7b.py ... ok
test_a_instantiate_class_0 (__main__.lab7b.test_a_instantiate_class_0)
[Lab 7] - [Investigation 1] - [Part 2] - Test for Creating object - should fail with 4 arguments ... ok
test_a_instantiate_class_1 (__main__.lab7b.test_a_instantiate_class_1)
[Lab 7] - [Investigation 1] - [Part 2] - Test for Creating object - should fail with string arguments ... ok
test_b1_change_time (__main__.lab7b.test_b1_change_time)
[Lab 7] - [Investigation 1] - [Part 2] - Test for change_time() with +1800 seconds ... ok
test_b2_change_time (__main__.lab7b.test_b2_change_time)
[Lab 7] - [Investigation 1] - [Part 2] - Test for change_time() with -1800 seconds ... ok

----------------------------------------------------------------------
Ran 6 tests in 0.004s

OK
sarjina@fedora:~/ops445/lab7$ python3 ./CheckLab7.py -f -v lab7c
test_0 (__main__.lab7c.test_0)
[Lab 7] - [Investigation 1] - [Part 3] - Test for file creation: ./lab7c.py ... ok
test_1 (__main__.lab7c.test_1)
[Lab 7] - [Investigation 1] - [Part 3] - Test for file creation: ./lab7c1.py ... FAIL

======================================================================
FAIL: test_1 (__main__.lab7c.test_1)
[Lab 7] - [Investigation 1] - [Part 3] - Test for file creation: ./lab7c1.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sarjina/ops445/lab7/./CheckLab7.py", line 172, in test_1
    self.assertTrue(os.path.exists('./lab7c1.py'), msg=error_output)
AssertionError: False is not true : file lab7c1.py cannot be fount(HINT: make sure you AND your file are in the correct directory)

----------------------------------------------------------------------
Ran 2 tests in 0.004s

FAILED (failures=1)
sarjina@fedora:~/ops445/lab7$ python3 ./CheckLab7.py -f -v lab7d
test_0 (__main__.lab7d.test_0)
[Lab 7] - [Investigation 2] - [Part 1] - Test for file creation: ./lab7d.py ... ok
test_a_instantiate_class_0 (__main__.lab7d.test_a_instantiate_class_0)
[Lab 7] - [Investigation 2] - [Part 1] - Test for Creating object in ./lab7d.py - should fail with 4 arguments ... ok
test_a_instantiate_class_1 (__main__.lab7d.test_a_instantiate_class_1)
[Lab 7] - [Investigation 2] - [Part 1] - Test for Creating object in ./lab7d.py - should fail with string arguments ... ok
test_b1_time_to_sec (__main__.lab7d.test_b1_time_to_sec)
[Lab 7] - [Investigation 2] - [Part 1] - Test for time_to_sec() method in ./lab7d.py ... ok
test_b2_format_time (__main__.lab7d.test_b2_format_time)
[Lab 7] - [Investigation 2] - [Part 1] - Test for format_time() method in ./lab7d.py ... ok
test_b3_sum_times (__main__.lab7d.test_b3_sum_times)
[Lab 7] - [Investigation 2] - [Part 1] - Test for sum_times() method in ./lab7d.py ... ok
test_b4_change_time (__main__.lab7d.test_b4_change_time)
[Lab 7] - [Investigation 2] - [Part 1] - Test for change_time() method in ./lab7d.py ... ok
test_b5_valid_time (__main__.lab7d.test_b5_valid_time)
[Lab 7] - [Investigation 2] - [Part 1] - Test for invalid time using valid_time() method in ./lab7d.py ... ok
test_b6_valid_time (__main__.lab7d.test_b6_valid_time)
[Lab 7] - [Investigation 2] - [Part 1] - Test for valid time using valid_time() method in ./lab7d.py ... ok
test_b7_sec_to_time (__main__.lab7d.test_b7_sec_to_time)
[Lab 7] - [Investigation 2] - [Part 1] - Test for sec_to_time() function in ./lab7d.py ... ok

----------------------------------------------------------------------
Ran 10 tests in 0.010s

OK
sarjina@fedora:~/ops445/lab7$ python3 ./CheckLab7.py -f -v lab7e
test_0 (__main__.lab7e.test_0)
[Lab 7] - [Investigation 2] - [Part 2] - Special object methods - Test for file creation: ./lab7e.py ... ok
test_b1_import (__main__.lab7e.test_b1_import)
[Lab 7] - [Investigation 2] - [Part 2] - Test for importing ./lab7e.py ... ok
test_b2_create_object (__main__.lab7e.test_b2_create_object)
[Lab 7] - [Investigation 2] - [Part 2] - Test for creating time object in ./lab7e.py ... ok
test_b3_str (__main__.lab7e.test_b3_str)
[Lab 7] - [Investigation 2] - [Part 2] - Test for __str__ method in ./lab7e.py ... ok
test_b4_repr (__main__.lab7e.test_b4_repr)
[Lab 7] - [Investigation 2] - [Part 2] - Test for __repr__ method in ./lab7e.py ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
sarjina@fedora:~/ops445/lab7$ python3 ./CheckLab7.py -f -v lab7f
test_0 (__main__.lab7f.test_0)
[Lab 7] - [Investigation 2] - [Part 3] - Operator overloading - Test for file creation: ./lab7f.py ... ok
test_b1_import (__main__.lab7f.test_b1_import)
[Lab 7] - [Investigation 2] - [Part 3] - Test for importing ./lab7f.py ... ok
test_b2_create_object (__main__.lab7f.test_b2_create_object)
[Lab 7] - [Investigation 2] - [Part 3] - Test for creating time object in ./lab7f.py ... ok
test_b3_operator_overloading (__main__.lab7f.test_b3_operator_overloading)
[Lab 7] - [Investigation 2] - [Part 3] - Test for operator overloading for + in ./lab7f.py ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.003s

OK
sarjina@fedora:~/ops445/lab7$ python3 ./CheckLab7.py -f -v lab7i
test_0 (__main__.lab7i.test_0)
[Lab 7] - [Investigation 3] - [Part 3] - Local/Global Scope - Test for file creation: ./lab7i.py ... ok
test_b1_run (__main__.lab7i.test_b1_run)
[Lab 7] - [Investigation 3] - [Part 3] - Global scope - Test for successful execution: ./lab7i.py ... ok
test_b2_run (__main__.lab7i.test_b2_run)
[Lab 7] - [Investigation 3] - [Part 3] - Global scope - Test for correct output: ./lab7i.py ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.065s

OK
